import "@/app/bootstrap.scss";
import { ClientRoot } from "./Root";
import Theme from "@/components/UI/Theme";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja" suppressHydrationWarning>
      <body>
        <Theme.Initialize />
        <ClientRoot>{children}</ClientRoot>
      </body>
    </html>
  );
}
