import "@/app/bootstrap.scss";
import { Root } from "./Root";

export const metadata = {
  title: 'Buff',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <Root>
      {children}
    </Root>
  );
}
